In [429]:
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

In [430]:
X = []
Y = []
with open('train.csv', 'r') as f:
    print(f.readline())
    for line in f:
        data = line.split(',')
        _id = int(data[0])
        y = float(data[-1])
        x = [float(_x) for _x in data[1:-1]]
        
        X.append(x)
        Y.append(y)


id,l0,l1,l2,l3,l4,l5,l6,l7,y



In [431]:
X = np.array(X)
Y = np.array(Y)

In [432]:
W=np.array([0,0,0,0,0,0,0,-0.05])

In [433]:
myY = X.dot(W)
myY

array([ 0.0663158 ,  0.04138363, -0.15113494, ..., -0.034454  ,
       -0.00538679, -0.02983227])

In [434]:
((X.dot(W) - Y)**2).mean()**0.5

2.5846212980730026

In [435]:
Xtest = []
Ytest = []
with open('test_without_labels.csv', 'r') as f:
    print(f.readline())
    for line in f:
        data = line.split(',')
        _id = int(data[0])
        y = float(data[-1])
        x = [float(_x) for _x in data[1:]]
        
        Xtest.append(x)


id,l0,l1,l2,l3,l4,l5,l6,l7



In [436]:
Xtest = np.array(Xtest)
Ytest = []

In [437]:
Ytest


[]

In [438]:
Xtest

array([[-0.26940413,  0.03119274, -0.63124376, ...,  0.12231192,
         0.39717517,  0.45454864],
       [-1.51604182,  0.84912314, -0.77080089, ..., -0.90479862,
        -1.64635456, -4.34018441],
       [ 0.02076198,  0.24366167,  0.81883505, ..., -1.04673384,
         0.66733266, -1.05836792],
       ...,
       [ 0.59790498,  0.80156698,  0.69063792, ...,  5.98943855,
         0.68376694,  0.21714672],
       [ 2.04681276,  0.52753404, -0.12253917, ..., -1.55551133,
        -0.40010153, -1.73078178],
       [-1.46086158, -1.0050499 ,  0.5742688 , ..., -0.87442981,
         1.28505272,  0.19621839]])

In [439]:
Xtest.shape

(1500, 8)

In [440]:
i = 0
for _x in Xtest:
    distance = ((X - _x)**2).sum(axis=1)**0.5
    distance.argsort()
    yNN = Y[distance.argsort()[:5]]
    unique, counts = np.unique(yNN, return_counts=True)
    my_dict = dict(zip(unique, counts))
    key_max = int(max(my_dict.keys(), key=(lambda k: my_dict[k])))
    Ytest.append([i, key_max])
    i=int(i+1)
    

In [441]:
Ytest = np.array(Ytest)
Ytest.shape
Ytest

array([[   0,    3],
       [   1,    3],
       [   2,    3],
       ...,
       [1497,    0],
       [1498,    2],
       [1499,    3]])

In [450]:
np.savetxt("foo2.csv", Ytest, fmt='%i', delimiter=';', header="id; y", comments='')